- name: Update homebrew
  homebrew:
    name: git
    state: latest
    update_homebrew: true
  tags:
    - homebrew

- name: Install homebrew casks
  command: brew install {{ homebrew_casks|join(" ") }}
  tags:
    - homebrew

- name: Install homebrew formulae
  homebrew:
    name: "{{ homebrew_formulae }}"
    state: latest
  tags:
    - homebrew

- name: Install node
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    nvm install --lts
    nvm use --lts
  args:
    creates: "{{ lookup('env', 'HOME') }}/.nvm/nvm.sh"
  tags: nodejs

- name: Enable corepack
  shell: |
    corepack enable
    corepack enable pnpm
    corepack use pnpm@latest
  tags:
    - nodejs

- name: Install rust
  shell: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
    rustup toolchain install nightly
    rustup default nightly
  tags:
    - rust

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  args:
    creates: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  tags:
    - zsh

- name: Install p10k
  git:
    repo: git@github.com:romkatv/powerlevel10k.git
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/powerlevel10k"
    key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    accept_hostkey: yes
    depth: 1
  tags:
    - zsh

- name: Install Copilot CLI
  shell: |
    pnpm add -g @githubnext/github-copilot-cli
  tags:
    - ai

- name: Authenticate with Github CLIs
  copy:
    content: "{{ item.text }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ item.file }}"
  with_items:
    - file: .copilot-cli-access-token
      text: "{{ copilot_cli_access_token }}"
    - file: .copilot-cli-copilot-token
      text: "{{ copilot_cli_copilot_token }}"
    - file: .config/gh/hosts.yml
      text: |
        github.com:
            oauth_token: {{ github_cli_token }}
            user: crcarrick
            git_protocol: ssh
  tags:
    - ai
    - github
