homebrew_casks:
  - bitwarden
  - discord
  - iterm2
  - kindle
  - microsoft-edge
  - notion
  - raycast
  - slack
  - spotify
  - visual-studio-code
  - zoom

homebrew_formulae:
  - bat
  - bitwarden-cli
  - caddy
  - dockutil
  - exa
  - fzf
  - git
  - gh
  - go
  - lazydocker
  - lazygit
  - lesspipe
  - mas
  - mycli
  - nvm
  - pgcli
  - pyenv
  - sqlite
  - watchman
  - yank
  - zsh-completions
  - zsh-autosuggestions
  - zsh-syntax-highlighting
