vscode_extensions:
  - arcanis.vscode-zipfs
  - bierner.emojisense
  - bradlc.vscode-tailwindcss
  - bungcip.better-toml
  - dbaeumer.vscode-eslint
  - dracula-theme.theme-dracula
  - eamodio.gitlens
  - EditorConfig.EditorConfig
  - esbenp.prettier-vscode
  - fauna.fauna
  - formulahendry.auto-rename-tag
  - github.copilot
  - github.vscode-pull-request-github
  - golang.go
  - GraphQL.vscode-graphql
  - GraphQL.vscode-graphql-syntax
  - Kasik96.swift
  - lanza.lldb-vscode
  - ms-python.isort
  - ms-python.python
  - ms-python.vscode-pylance
  - Orta.vscode-jest
  - Orta.vscode-twoslash-queries
  - PKief.material-icon-theme
  - redhat.vscode-xml
  - rust-lang.rust-analyzer
  - styled-components.vscode-styled-components
  - unifiedjs.vscode-mdx
  - wayou.vscode-todo-highlight
  - xyc.vscode-mdx-preview
