vscode_extensions:
  - 4ops.terraform
  - arcanis.vscode-zipfs
  - bierner.emojisense
  - bradlc.vscode-tailwindcss
  - crcarrick.fs-events-cmd
  - dbaeumer.vscode-eslint
  - dracula-theme.theme-dracula
  - eamodio.gitlens
  - EditorConfig.EditorConfig
  - esbenp.prettier-vscode
  - github.copilot
  - github.copilot-chat
  - github.vscode-pull-request-github
  - golang.go
  - GraphQL.vscode-graphql
  - GraphQL.vscode-graphql-syntax
  - Kasik96.swift
  - lanza.lldb-vscode
  - ms-python.black-formatter
  - ms-python.debugpy
  - ms-python.flake8
  - ms-python.isort
  - ms-python.python
  - ms-python.vscode-pylance
  - Orta.vscode-jest
  - Orta.vscode-twoslash-queries
  - PKief.material-icon-theme
  - redhat.vscode-xml
  - rust-lang.rust-analyzer
  - styled-components.vscode-styled-components
  - tamasfe.even-better-toml
  - wayou.vscode-todo-highlight
  - yoavbls.pretty-ts-errors
